import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import path from "node:path";
import { readFileSync } from "node:fs";

const root = path.resolve(__dirname, "../../..");
export default defineConfig({
  root: __dirname,
  plugins: [react(), {
    name: "synthetic-po-pdfs",
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const match = req.url?.match(/^\/api\/purchase-indents\/(\d+)\/items\/(\d+)\/purchase-order\.pdf/);
        if (!match) return next();
        const file = ({ 11: "bulk-linked.pdf", 12: "store-unlinked.pdf", 13: "bulk-unlinked.pdf", 14: "store-linked.pdf", 15: "store-unlinked.pdf" } as Record<number, string>)[Number(match[2])];
        if (!file) { res.statusCode = 404; res.end("Unknown synthetic PO"); return; }
        // This fixture serves real PDFs generated by the tested PDFKit builder.
        // It has no database or write-through path to a live business API.
        res.setHeader("Content-Type", "application/pdf");
        res.setHeader("Content-Disposition", `${req.url?.includes("preview=1") ? "inline" : "attachment"}; filename="SYNTHETIC-PO-${match[2]}.pdf"`);
        res.end(readFileSync(path.join(root, "reports/part-c", file)));
      });
    },
  }],
  resolve: { alias: { "@": path.join(root, "client/src"), "@shared": path.join(root, "shared") } },
});