/**
 * Opt-in real PostgreSQL LABOUR-01 test. Run only against the disposable dev
 * database: LABOUR01_PG_TEST=1 DEV_DATABASE_URL=... npx vitest run tests/labour01WorkersPostgres.test.ts
 * All DDL/DML is restricted to a unique schema; public is read only (LIKE).
 */
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { eq } from "drizzle-orm";
import { labourLogs, labourLogWorkers } from "../shared/schema";
import { insertLabourWithWorkers, readWorkerNames, replaceLabourWorkers } from "../server/labourWorkers";

const enabled = process.env.LABOUR01_PG_TEST === "1";
const url = process.env.DEV_DATABASE_URL;
const suite = enabled ? describe : describe.skip;
const schemaName = `labour01_test_${process.pid}_${Date.now().toString(36)}`;
let admin: pg.Client | undefined;
let pool: pg.Pool | undefined;
let created = false;

suite("LABOUR-01 isolated real PostgreSQL", () => {
  beforeAll(async () => {
    if (!url) throw new Error("LABOUR01_PG_TEST requires DEV_DATABASE_URL");
    admin = new pg.Client({ connectionString: url });
    await admin.connect();
    const target = await admin.query("SELECT current_database() AS name");
    if (target.rows[0]?.name !== "sitelog_dev") {
      throw new Error("LABOUR01 test refuses a database other than sitelog_dev");
    }
    const parent = await admin.query("SELECT to_regclass('public.labour_logs') AS parent");
    if (!parent.rows[0]?.parent) throw new Error("Expected existing public.labour_logs parent");
    // No defaults are copied: specifically, never reference the public serial sequence.
    // LIKE copies the actual deployed parent column types and NOT NULL constraints.
    await admin.query(`CREATE SCHEMA "${schemaName}"`);
    created = true;
    await admin.query(`CREATE TABLE "${schemaName}".labour_logs (LIKE public.labour_logs INCLUDING CONSTRAINTS)`);
    await admin.query(`ALTER TABLE "${schemaName}".labour_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`);
    await admin.query(`ALTER TABLE "${schemaName}".labour_logs ADD PRIMARY KEY (id)`);
    // Only this session's search_path is changed, never the database/public schema.
    await admin.query(`SET search_path TO "${schemaName}"`);
    await admin.query(readFileSync("migrations/0039_labour_log_workers.sql", "utf8"));
    pool = new pg.Pool({ connectionString: url, options: `-c search_path=${schemaName}`, max: 2 });
    const isolation = await pool.query("SELECT current_schema() AS name");
    expect(isolation.rows[0].name).toBe(schemaName);
  });

  afterAll(async () => {
    await pool?.end();
    try {
      if (created && admin) await admin.query(`DROP SCHEMA "${schemaName}" CASCADE`);
    } finally {
      await admin?.end();
    }
  });

  it("inserts, replaces, clears, cascades and copies names without inflating count", async () => {
    const db = drizzle(pool!);
    const dprId = 910001;
    const first = await db.transaction(tx => insertLabourWithWorkers(tx, dprId, [
      { category: "Skilled", count: 0 },
      { category: "Skilled", count: 1, workerNames: [" Ana ", " ", "Ana", " Bea "] },
    ]));
    expect(first).toHaveLength(2);
    expect(await readWorkerNames(db, first)).toMatchObject([
      { workerNames: [] }, { workerNames: ["Ana", "Ana", "Bea"] },
    ]);
    expect((await pool!.query("SELECT count(*)::int AS rows, sum(count)::int AS mandays FROM labour_logs")).rows[0])
      .toEqual({ rows: 2, mandays: 1 });
    // Real parent replacement, as in the full DPR save path.
    const replacement = await db.transaction(async tx => {
      const old = await readWorkerNames(tx, await tx.select().from(labourLogs).where(eq(labourLogs.dprId, dprId)));
      await tx.delete(labourLogs).where(eq(labourLogs.dprId, dprId));
      return insertLabourWithWorkers(tx, dprId, [
        { persistedId: old[1].id, category: "Skilled", count: 2 },
        { persistedId: old[0].id, category: "Skilled", count: 0, workerNames: [" New "] },
      ], old);
    });
    expect(await readWorkerNames(db, replacement)).toMatchObject([
      { workerNames: ["Ana", "Ana", "Bea"] }, { workerNames: ["New"] },
    ]);
    expect((await pool!.query("SELECT count(*)::int AS n FROM labour_log_workers")).rows[0].n).toBe(4);
    await db.transaction(tx => replaceLabourWorkers(tx, replacement, [{}, { workerNames: [] }]));
    expect(await readWorkerNames(db, replacement)).toMatchObject([
      { workerNames: ["Ana", "Ana", "Bea"] }, { workerNames: [] },
    ]);
    // Copy a row to a different DPR using the source aggregate's names.
    const source = (await readWorkerNames(db, replacement))[0];
    const copied = await db.transaction(tx => insertLabourWithWorkers(tx, 910002, [{
      category: source.category, gender: source.gender, count: source.count,
      task: source.task, contractor: source.contractor, boqItemId: source.boqItemId,
      structureId: source.structureId, workerNames: source.workerNames,
    }]));
    expect((await readWorkerNames(db, copied))[0]).toMatchObject({
      category: "Skilled", count: 2, workerNames: ["Ana", "Ana", "Bea"],
    });
    expect((await pool!.query("SELECT sum(count)::int AS mandays FROM labour_logs WHERE dpr_id = $1", [dprId])).rows[0].mandays).toBe(2);
    // A joined worker report would multiply the parent; the canonical parent count must not.
    expect((await pool!.query("SELECT sum(l.count)::int AS multiplied FROM labour_logs l JOIN labour_log_workers w ON w.labour_log_id = l.id WHERE l.dpr_id = $1", [dprId])).rows[0].multiplied).toBe(6);
    await db.delete(labourLogs).where(eq(labourLogs.id, replacement[0].id));
    expect((await pool!.query("SELECT count(*)::int AS n FROM labour_log_workers WHERE labour_log_id = $1", [replacement[0].id])).rows[0].n).toBe(0);
  });

  it("rejects missing identity and a real FK violation rolls back parent deletion", async () => {
    const db = drizzle(pool!);
    const [saved] = await db.transaction(tx => insertLabourWithWorkers(tx, 910003, [
      { category: "Unskilled", count: 1, workerNames: ["Original"] },
    ]));
    await expect(db.transaction(async tx => {
      const old = await readWorkerNames(tx, await tx.select().from(labourLogs).where(eq(labourLogs.dprId, 910003)));
      await tx.delete(labourLogs).where(eq(labourLogs.dprId, 910003));
      await insertLabourWithWorkers(tx, 910003, [{ category: "Unskilled", count: 7 }], old);
    })).rejects.toThrow("Reload saved labour row identities");
    expect((await readWorkerNames(db, [saved]))[0].workerNames).toEqual(["Original"]);
    await expect(db.transaction(async tx => {
      await tx.delete(labourLogs).where(eq(labourLogs.id, saved.id));
      await tx.insert(labourLogWorkers).values({ labourLogId: saved.id, name: "Orphan" });
    })).rejects.toMatchObject({ code: "23503" });
    expect((await readWorkerNames(db, [saved]))[0].workerNames).toEqual(["Original"]);
    expect((await pool!.query("SELECT count(*)::int AS n FROM labour_logs WHERE id = $1", [saved.id])).rows[0].n).toBe(1);
  });
});