CREATE TABLE IF NOT EXISTS purchase_orders (
  id serial PRIMARY KEY,
  purchase_indent_id integer NOT NULL REFERENCES purchase_indents(id),
  purchase_indent_item_id integer NOT NULL REFERENCES purchase_indent_items(id),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'approved', 'rejected')),
  order_no text,
  vendor_id integer REFERENCES vendors(id) ON DELETE SET NULL,
  vendor_name text NOT NULL,
  vendor_business_name text,
  vendor_gst text,
  vendor_pan text,
  vendor_address text,
  description text NOT NULL,
  spec text,
  quantity real NOT NULL,
  unit text NOT NULL,
  rate real,
  expected_delivery text,
  payment_terms text,
  destination text,
  raised_by_user_id integer NOT NULL REFERENCES users(id),
  raised_at timestamp NOT NULL DEFAULT now(),
  submitted_at timestamp,
  approved_by_user_id integer REFERENCES users(id),
  approved_at timestamp,
  rejection_reason text,
  created_at timestamp NOT NULL DEFAULT now(),
  updated_at timestamp NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS purchase_orders_one_active_per_item ON purchase_orders (purchase_indent_item_id) WHERE status <> 'rejected';