// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/concrete-calc/ConcreteCalcBottom.tsx": () => import("../components/mockups/concrete-calc/ConcreteCalcBottom.tsx"),
  "./components/mockups/concrete-calc/ConcreteCalcTop.tsx": () => import("../components/mockups/concrete-calc/ConcreteCalcTop.tsx"),
  "./components/mockups/concrete-calc/ConcreteEstimatesList.tsx": () => import("../components/mockups/concrete-calc/ConcreteEstimatesList.tsx"),
  "./components/mockups/concrete-calc/ConcreteScenarios.tsx": () => import("../components/mockups/concrete-calc/ConcreteScenarios.tsx"),
  "./components/mockups/concrete-calc/LoginHub.tsx": () => import("../components/mockups/concrete-calc/LoginHub.tsx"),
  "./components/mockups/concrete-calc/ReportsTab.tsx": () => import("../components/mockups/concrete-calc/ReportsTab.tsx"),
  "./components/mockups/mix-portal-login/LoginPage.tsx": () => import("../components/mockups/mix-portal-login/LoginPage.tsx"),
  "./components/mockups/plant-home/PlantHome.tsx": () => import("../components/mockups/plant-home/PlantHome.tsx"),
  "./components/mockups/rmc-dispatch/RmcDispatch.tsx": () => import("../components/mockups/rmc-dispatch/RmcDispatch.tsx"),
  "./components/mockups/rmc-mix-designs/RmcMixDesigns.tsx": () => import("../components/mockups/rmc-mix-designs/RmcMixDesigns.tsx"),
  "./components/mockups/site-report-home/Dashboard.tsx": () => import("../components/mockups/site-report-home/Dashboard.tsx")
};
