import { type SectionKey, type PermissionMatrix, SECTION_KEYS, emptyMatrix, type SessionPolicy } from "./permissions";

export type RoleTemplateKey =
  | "owner" | "company_admin" | "project_manager" | "senior_engineer"
  | "site_engineer" | "supervisor" | "storekeeper" | "plant_manager"
  | "plant_supervisor" | "plant_operator" | "equipment_incharge"
  | "procurement_user" | "billing_accounts" | "viewer_auditor";

export const ROLE_TEMPLATE_LABELS: Record<RoleTemplateKey, string> = {
  owner:             "Owner / Primary Admin",
  company_admin:     "Company Admin",
  project_manager:   "Project Manager",
  senior_engineer:   "Senior Engineer",
  site_engineer:     "Site Engineer",
  supervisor:        "Supervisor",
  storekeeper:       "Storekeeper",
  plant_manager:     "Plant Manager",
  plant_supervisor:  "Plant Supervisor",
  plant_operator:    "Plant Operator",
  equipment_incharge:"Equipment Incharge",
  procurement_user:  "Procurement User",
  billing_accounts:  "Billing / Accounts User",
  viewer_auditor:    "Viewer / Auditor",
};

export const ROLE_TEMPLATE_KEYS: RoleTemplateKey[] = [
  "owner", "company_admin", "project_manager", "senior_engineer",
  "site_engineer", "supervisor", "storekeeper", "plant_manager",
  "plant_supervisor", "plant_operator", "equipment_incharge",
  "procurement_user", "billing_accounts", "viewer_auditor",
];

export const ROLE_DEFAULT_SESSION_POLICY: Record<RoleTemplateKey, SessionPolicy> = {
  owner:              "1h",
  company_admin:      "1h",
  project_manager:    "7d",
  senior_engineer:    "7d",
  site_engineer:      "7d",
  supervisor:         "7d",
  storekeeper:        "7d",
  plant_manager:      "7d",
  plant_supervisor:   "7d",
  plant_operator:     "7d",
  equipment_incharge: "7d",
  procurement_user:   "7d",
  billing_accounts:   "7d",
  viewer_auditor:     "7d",
};

type P = {
  view?: boolean; create?: boolean; edit?: boolean; delete?: boolean;
  view_reports?: boolean; export?: boolean; approve?: boolean; notify?: boolean;
};

function p(vals: P) {
  return {
    view: false, create: false, edit: false, delete: false,
    view_reports: false, export: false, approve: false, notify: false,
    ...vals,
  };
}

const VIEW = p({ view: true });
const VIEW_REPORTS = p({ view: true, view_reports: true, export: true });
const FULL = p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true, approve: true });
const CREATE_EDIT = p({ view: true, create: true, edit: true, view_reports: true, export: true });
const CREATE_ONLY = p({ view: true, create: true });

type SectionOverrides = Partial<Record<SectionKey, P>>;

function buildMatrix(base: P, overrides: SectionOverrides): PermissionMatrix {
  const m = emptyMatrix();
  for (const k of SECTION_KEYS) {
    m[k] = overrides[k] ? p(overrides[k]!) : { ...base };
  }
  return m;
}

const ROLE_MATRICES: Record<RoleTemplateKey, PermissionMatrix> = {
  owner: buildMatrix(
    FULL,
    { notify: p({}) } as SectionOverrides
  ),

  company_admin: buildMatrix(
    FULL,
    { notify: p({}) } as SectionOverrides
  ),

  project_manager: buildMatrix(p({}), {
    dashboard:              VIEW_REPORTS,
    hmp_hub:                VIEW,
    site_hub:               VIEW,
    reports_hub:            VIEW,
    stores_hub:             VIEW,
    finance_hub:            VIEW,
    masters_hub:            VIEW,
    admin_hub:              p({}),
    rmc_hub:                p({}),
    site_dprs:              p({ view: true, create: true, edit: true, view_reports: true, export: true, approve: true }),
    site_materials:         CREATE_EDIT,
    site_procurement:       VIEW,
    purchase_indents_view:  p({ view: true, view_reports: true, export: true, approve: true }),
    purchase_indents_raise: p({ view: true, create: true }),
    purchase_indents_approve: p({ view: true, approve: true }),
    site_diesel:            VIEW,
    diesel_req_view:        p({ view: true, view_reports: true, export: true, approve: true }),
    diesel_req_raise:       p({ view: true, create: true }),
    diesel_req_approve:     p({ view: true, approve: true }),
    irn_view:               VIEW,
    irn_raise:              CREATE_ONLY,
    irn_approve:            p({ view: true, approve: true }),
    plant_shift_logs:       VIEW_REPORTS,
    plant_manpower_review:  VIEW_REPORTS,
    plant_heating:          VIEW_REPORTS,
    plant_heating_trends:   VIEW_REPORTS,
    plant_equipment:        VIEW_REPORTS,
    plant_generator_logs:   VIEW_REPORTS,
    plant_maintenance:      VIEW_REPORTS,
    plant_production:       VIEW_REPORTS,
    plant_materials:        VIEW_REPORTS,
    plant_bitumen:          VIEW_REPORTS,
    plant_ldo:              VIEW_REPORTS,
    plant_daily_reports:    VIEW_REPORTS,
    plant_stock:            VIEW_REPORTS,
    plant_ldo_reconciliation: VIEW_REPORTS,
    plant_variance:         VIEW_REPORTS,
    plant_audit:            VIEW_REPORTS,
    plant_diesel_proc:      VIEW_REPORTS,
    rmc_batch_records:      VIEW,
    rmc_mix_designs:        VIEW,
    rmc_cube_tests:         VIEW,
    rmc_raw_materials:      VIEW,
    rmc_delivery_challans:  VIEW,
    rmc_daily_report:       VIEW_REPORTS,
    vendor_bills:           VIEW,
    vendor_bills_view:      VIEW_REPORTS,
    vendor_bills_raise:     CREATE_ONLY,
    vendor_bills_verify:    p({ view: true, create: true }),
    vendor_bills_approve:   p({ view: true, approve: true }),
    vendor_bill_aliases:    VIEW,
    reports:                VIEW_REPORTS,
    report_management:      VIEW_REPORTS,
    report_site_purchases:  VIEW_REPORTS,
    stores_inventory:       VIEW_REPORTS,
    estimator_portal:       VIEW,
    mix_calculator:         VIEW,
    concrete_calculator:    VIEW,
    qto_boq:                VIEW_REPORTS,
    rate_cards:             VIEW,
    master_parties:         VIEW,
    master_materials:       VIEW,
    master_equipment:       VIEW,
    master_personnel:       VIEW,
  }),

  senior_engineer: buildMatrix(p({}), {
    dashboard:              VIEW_REPORTS,
    hmp_hub:                VIEW,
    site_hub:               VIEW,
    reports_hub:            VIEW,
    stores_hub:             VIEW,
    finance_hub:            VIEW,
    masters_hub:            VIEW,
    site_dprs:              CREATE_EDIT,
    site_materials:         CREATE_EDIT,
    purchase_indents_view:  VIEW,
    purchase_indents_raise: CREATE_ONLY,
    diesel_req_view:        VIEW,
    diesel_req_raise:       CREATE_ONLY,
    irn_view:               VIEW,
    irn_raise:              CREATE_ONLY,
    irn_approve:            VIEW,
    plant_shift_logs:       CREATE_EDIT,
    plant_manpower_review:  VIEW_REPORTS,
    plant_heating:          CREATE_EDIT,
    plant_heating_trends:   VIEW_REPORTS,
    plant_equipment:        CREATE_EDIT,
    plant_generator_logs:   CREATE_EDIT,
    plant_maintenance:      CREATE_EDIT,
    plant_production:       CREATE_EDIT,
    plant_materials:        CREATE_EDIT,
    plant_bitumen:          VIEW_REPORTS,
    plant_ldo:              VIEW_REPORTS,
    plant_daily_reports:    VIEW_REPORTS,
    plant_stock:            VIEW_REPORTS,
    plant_ldo_reconciliation: VIEW_REPORTS,
    plant_variance:         VIEW_REPORTS,
    plant_audit:            VIEW_REPORTS,
    plant_diesel_proc:      VIEW_REPORTS,
    vendor_bills_view:      VIEW,
    report_management:      VIEW_REPORTS,
    report_site_purchases:  VIEW_REPORTS,
    stores_inventory:       CREATE_EDIT,
    mix_calculator:         VIEW,
    qto_boq:                VIEW_REPORTS,
    rate_cards:             VIEW,
    master_parties:         CREATE_EDIT,
    master_materials:       CREATE_EDIT,
    master_equipment:       CREATE_EDIT,
    master_personnel:       CREATE_EDIT,
  }),

  site_engineer: buildMatrix(p({}), {
    dashboard:              VIEW,
    site_hub:               VIEW,
    reports_hub:            VIEW,
    site_dprs:              CREATE_ONLY,
    site_materials:         CREATE_ONLY,
    purchase_indents_view:  VIEW,
    diesel_req_view:        VIEW,
    diesel_req_raise:       CREATE_ONLY,
    irn_view:               VIEW,
    irn_raise:              CREATE_ONLY,
    plant_shift_logs:       VIEW,
    plant_heating:          VIEW,
    plant_equipment:        VIEW,
    plant_production:       VIEW,
    plant_materials:        VIEW,
    plant_daily_reports:    VIEW,
    plant_stock:            VIEW,
    report_site_purchases:  VIEW_REPORTS,
    master_parties:         VIEW,
    master_materials:       VIEW,
    master_equipment:       VIEW,
    master_personnel:       VIEW,
  }),

  supervisor: buildMatrix(p({}), {
    dashboard:              VIEW,
    site_hub:               VIEW,
    site_dprs:              CREATE_ONLY,
    site_materials:         CREATE_ONLY,
    purchase_indents_view:  VIEW,
    diesel_req_view:        VIEW,
    irn_view:               VIEW,
    plant_shift_logs:       VIEW,
    plant_production:       VIEW,
    plant_materials:        VIEW,
    master_parties:         VIEW,
    master_equipment:       VIEW,
  }),

  storekeeper: buildMatrix(p({}), {
    dashboard:              VIEW,
    stores_hub:             VIEW,
    masters_hub:            VIEW,
    irn_view:               VIEW,
    irn_raise:              p({ view: true, create: true, edit: true }),
    irn_approve:            p({ view: true, create: true, approve: true }),
    stores_inventory:       p({ view: true, create: true, edit: true, view_reports: true, export: true }),
    plant_materials:        CREATE_ONLY,
    master_materials:       VIEW,
    master_parties:         VIEW,
    report_site_purchases:  VIEW,
  }),

  plant_manager: buildMatrix(p({}), {
    dashboard:              VIEW_REPORTS,
    hmp_hub:                VIEW,
    reports_hub:            VIEW,
    finance_hub:            VIEW,
    masters_hub:            VIEW,
    plant_shift_logs:       p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true, approve: true }),
    plant_manpower_review:  VIEW_REPORTS,
    plant_heating:          p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true }),
    plant_heating_trends:   VIEW_REPORTS,
    plant_equipment:        p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true }),
    plant_generator_logs:   CREATE_EDIT,
    plant_maintenance:      CREATE_EDIT,
    plant_production:       p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true }),
    plant_materials:        p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true, approve: true }),
    plant_bitumen:          VIEW_REPORTS,
    plant_ldo:              VIEW_REPORTS,
    plant_daily_reports:    VIEW_REPORTS,
    plant_stock:            VIEW_REPORTS,
    plant_ldo_reconciliation: VIEW_REPORTS,
    plant_variance:         VIEW_REPORTS,
    plant_audit:            VIEW_REPORTS,
    plant_diesel_proc:      VIEW_REPORTS,
    purchase_indents_view:  VIEW,
    purchase_indents_approve: p({ view: true, approve: true }),
    diesel_req_view:        VIEW,
    diesel_req_approve:     p({ view: true, approve: true }),
    irn_view:               VIEW,
    irn_approve:            p({ view: true, approve: true }),
    vendor_bills_view:      VIEW,
    report_management:      VIEW_REPORTS,
    master_parties:         CREATE_EDIT,
    master_materials:       CREATE_EDIT,
    master_equipment:       CREATE_EDIT,
    master_personnel:       CREATE_EDIT,
  }),

  plant_supervisor: buildMatrix(p({}), {
    dashboard:              VIEW,
    hmp_hub:                VIEW,
    plant_shift_logs:       CREATE_EDIT,
    plant_manpower_review:  VIEW,
    plant_heating:          CREATE_EDIT,
    plant_heating_trends:   VIEW,
    plant_equipment:        CREATE_EDIT,
    plant_generator_logs:   CREATE_EDIT,
    plant_maintenance:      CREATE_EDIT,
    plant_production:       CREATE_EDIT,
    plant_materials:        CREATE_EDIT,
    plant_bitumen:          VIEW,
    plant_ldo:              VIEW,
    plant_daily_reports:    VIEW_REPORTS,
    plant_stock:            VIEW,
    plant_variance:         VIEW,
    master_parties:         VIEW,
    master_materials:       VIEW,
    master_equipment:       VIEW,
  }),

  plant_operator: buildMatrix(p({}), {
    dashboard:              VIEW,
    hmp_hub:                VIEW,
    plant_shift_logs:       CREATE_ONLY,
    plant_heating:          CREATE_ONLY,
    plant_equipment:        CREATE_ONLY,
    plant_generator_logs:   CREATE_ONLY,
    plant_production:       CREATE_ONLY,
    plant_materials:        VIEW,
    plant_bitumen:          VIEW,
    plant_ldo:              VIEW,
    plant_daily_reports:    VIEW,
    master_materials:       VIEW,
    master_equipment:       VIEW,
  }),

  equipment_incharge: buildMatrix(p({}), {
    dashboard:              VIEW,
    hmp_hub:                VIEW,
    plant_shift_logs:       VIEW,
    plant_equipment:        CREATE_EDIT,
    plant_generator_logs:   CREATE_EDIT,
    plant_maintenance:      p({ view: true, create: true, edit: true, delete: true, view_reports: true, export: true }),
    plant_bitumen:          VIEW,
    plant_ldo:              VIEW,
    plant_diesel_proc:      VIEW_REPORTS,
    diesel_req_view:        VIEW,
    diesel_req_raise:       CREATE_ONLY,
    master_equipment:       CREATE_EDIT,
  }),

  procurement_user: buildMatrix(p({}), {
    dashboard:              VIEW,
    finance_hub:            VIEW,
    site_hub:               VIEW,
    purchase_indents_view:  VIEW,
    purchase_indents_raise: CREATE_EDIT,
    diesel_req_view:        VIEW,
    diesel_req_raise:       CREATE_EDIT,
    irn_view:               VIEW,
    irn_raise:              CREATE_ONLY,
    vendor_bills_view:      VIEW,
    rate_cards:             VIEW,
    master_parties:         VIEW,
    master_materials:       VIEW,
  }),

  billing_accounts: buildMatrix(p({}), {
    dashboard:              VIEW_REPORTS,
    finance_hub:            VIEW,
    reports_hub:            VIEW,
    vendor_bills:           VIEW,
    vendor_bills_view:      p({ view: true, view_reports: true, export: true, approve: true }),
    vendor_bills_raise:     CREATE_ONLY,
    vendor_bills_verify:    p({ view: true, create: true }),
    vendor_bills_approve:   p({ view: true, approve: true }),
    vendor_bill_aliases:    p({ view: true, edit: true }),
    reports:                VIEW_REPORTS,
    report_management:      VIEW_REPORTS,
    report_site_purchases:  VIEW_REPORTS,
    estimator_portal:       VIEW,
    mix_calculator:         VIEW,
    concrete_calculator:    VIEW,
    qto_boq:                VIEW_REPORTS,
    rate_cards:             p({ view: true, edit: true }),
    master_parties:         VIEW,
  }),

  viewer_auditor: buildMatrix(p({}), {
    dashboard:              VIEW_REPORTS,
    hmp_hub:                VIEW,
    site_hub:               VIEW,
    reports_hub:            VIEW,
    stores_hub:             VIEW,
    finance_hub:            VIEW,
    masters_hub:            VIEW,
    site_dprs:              VIEW_REPORTS,
    site_materials:         VIEW_REPORTS,
    purchase_indents_view:  VIEW_REPORTS,
    diesel_req_view:        VIEW_REPORTS,
    irn_view:               VIEW,
    plant_shift_logs:       VIEW_REPORTS,
    plant_manpower_review:  VIEW_REPORTS,
    plant_heating:          VIEW_REPORTS,
    plant_heating_trends:   VIEW_REPORTS,
    plant_equipment:        VIEW_REPORTS,
    plant_generator_logs:   VIEW_REPORTS,
    plant_maintenance:      VIEW_REPORTS,
    plant_production:       VIEW_REPORTS,
    plant_materials:        VIEW_REPORTS,
    plant_bitumen:          VIEW_REPORTS,
    plant_ldo:              VIEW_REPORTS,
    plant_daily_reports:    VIEW_REPORTS,
    plant_stock:            VIEW_REPORTS,
    plant_ldo_reconciliation: VIEW_REPORTS,
    plant_variance:         VIEW_REPORTS,
    plant_audit:            VIEW_REPORTS,
    plant_diesel_proc:      VIEW_REPORTS,
    vendor_bills_view:      VIEW_REPORTS,
    report_management:      VIEW_REPORTS,
    report_site_purchases:  VIEW_REPORTS,
    stores_inventory:       VIEW_REPORTS,
    mix_calculator:         VIEW,
    qto_boq:                VIEW_REPORTS,
    rate_cards:             VIEW,
    master_parties:         VIEW,
    master_materials:       VIEW,
    master_equipment:       VIEW,
    master_personnel:       VIEW,
  }),
};

export function getRoleTemplate(roleKey: RoleTemplateKey): PermissionMatrix {
  return ROLE_MATRICES[roleKey];
}

export function getRoleDefaultSessionPolicy(roleKey: RoleTemplateKey): SessionPolicy {
  return ROLE_DEFAULT_SESSION_POLICY[roleKey];
}
